### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by emmiebyte** [Bluscream/VRChatLauncher#3]
I think this repository is missing instructions for installing VRChatLauncher.
While you're at it, you could add a precompiled binary for people who don't have visual studio 😊

**Comment by Bluscream** [comment]
When you got the EXE just drop it in your game folder and run it :)

**Comment by emmiebyte** [comment]
The fact that you have to put it in your game folder should probably be in the readme

**Comment by Bluscream** [comment]
Not really, it will copy itself there in later versions ^^
